<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Nodes [

<!ENTITY % NameValue "CDATA">
<!ENTITY % PropType "(I|S|D|L|H|B)">
<!ENTITY % VersionValue "CDATA">

<!ELEMENT Prp (#PCDATA)>
<!ELEMENT Node (Node|Prp)*>
<!ELEMENT Nodes (Node)+>

<!ATTLIST Nodes version CDATA "1">

<!ATTLIST Node name CDATA #REQUIRED>

<!ATTLIST Prp name CDATA #REQUIRED>
<!ATTLIST Prp type CDATA #REQUIRED>
<!ATTLIST Prp value CDATA #REQUIRED>
]>
<Nodes version="1">
	<Node name="root">
		<Node name="classes">
			<Node name="class0">
				<Node name="fields">
					<Node name="field0">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value=""/>
						<Prp name="name" type="S" value="Result"/>
						<Prp name="valuetype" type="I" value="0"/>
					</Node>
				</Node>
				<Node name="methods">
					<Node name="method0">
						<Prp name="membervalue" type="S" value=""/>
						<Prp name="name" type="S" value="Start"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="method1">
						<Prp name="membervalue" type="S" value="Calc._CalcStopODT"/>
						<Prp name="name" type="S" value="Close"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="method2">
						<Prp name="membervalue" type="S" value="Calc._CalcCalculateODT"/>
						<Prp name="name" type="S" value="Calculate"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
				</Node>
				<Prp name="name" type="S" value="Calculator"/>
			</Node>
		</Node>
		<Node name="data">
			<Node name="group0">
				<Node name="fields">
					<Node name="field0">
						<Node name="membervalue">
							<Node name="fields">
								<Node name="field0">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value=""/>
									<Prp name="name" type="S" value="Result"/>
									<Prp name="valuetype" type="I" value="0"/>
								</Node>
								<Node name="field1">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value=""/>
									<Prp name="name" type="S" value="Wnd"/>
									<Prp name="valuetype" type="I" value="0"/>
								</Node>
								<Node name="field2">
									<Prp name="checked" type="B" value="-1"/>
									<Prp name="membervalue" type="S" value="10"/>
									<Prp name="name" type="S" value="Row"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Node name="methods">
								<Node name="method0">
									<Prp name="checked" type="B" value="0"/>
									<Prp name="isini" type="B" value="0"/>
									<Prp name="membervalue" type="S" value="Calc._CalcStartODT"/>
									<Prp name="name" type="S" value="Start"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="method1">
									<Prp name="checked" type="B" value="0"/>
									<Prp name="isini" type="B" value="0"/>
									<Prp name="membervalue" type="S" value="Calc._CalcStopODT"/>
									<Prp name="name" type="S" value="Close"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
								<Node name="method2">
									<Prp name="checked" type="B" value="0"/>
									<Prp name="isini" type="B" value="0"/>
									<Prp name="membervalue" type="S" value="Calc._CalcCalculateODT"/>
									<Prp name="name" type="S" value="Calculate"/>
									<Prp name="valuetype" type="I" value="8"/>
								</Node>
							</Node>
							<Prp name="classref" type="S" value="Calculator"/>
							<Prp name="classreftype" type="I" value="0"/>
							<Prp name="name" type="S" value="Calculator{DAF72051-A69A-4566-9FF2-9CAA3FE74827}"/>
						</Node>
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="name" type="S" value="Calc"/>
						<Prp name="valuetype" type="I" value="9"/>
					</Node>
				</Node>
				<Node name="methods"/>
				<Prp name="checked" type="B" value="-1"/>
				<Prp name="name" type="S" value="CalcGroup"/>
			</Node>
		</Node>
	</Node>
</Nodes>